### ISSUE TITLE
Node 12 is deprecated and will be replaced by node 16 by summer 2023

### ISSUE THREAD

**Issue by brandonbirdj** [neofinancial/ticket-check-action#33]
See
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

This action is presently reporting the deprecation error when it runs.

**Comment by Mexmorize** [comment]
It would be amazing to get this working again <3

**Comment by joaquimcavalcanti** [comment]
Issue has been addressed #41
